name             'my_awesome_app'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures my_awesome_app'
long_description 'Installs/Configures my_awesome_app'
version          '0.1.0'

depends          'windows', '~> 1.36.1'
depends          'iis', '~> 4.0.0'
